project_id = "bgkafqfzqvurdgctckqn"

[functions.generate-contract]
verify_jwt = false

[functions.cleanup-old-contracts]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.get-users]
verify_jwt = true
